# ElastAlert2 Configuration
# Autonomous SOC Lab

es_host: opensearch
es_port: 9200
es_username: admin
es_password: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
use_ssl: false
verify_certs: false

writeback_index: elastalert_status
writeback_alias: elastalert_alerts
rules_folder: /opt/elastalert/rules

run_every:
  seconds: 30
buffer_time:
  minutes: 15
alert_time_limit:
  hours: 2

log_level: INFO
log_file: /var/log/elastalert/elastalert.log
disable_rules_on_error: false
max_scrolling_count: 990
alert_subject_prefix: "[SOC ALERT]"
old_query_limit:
  weeks: 1
use_local_time: true
add_metadata_alert: true
